#!/usr/bin/env python

import sys

from gpr20_raspi_ui import RaspiUI

from PyQt5.QtWidgets import QApplication

if __name__ == "__main__":

  # Creates the PyQt application
  app = QApplication(sys.argv)

  # Creates the RaspiUI instance
  ui = RaspiUI()

  # Shows the interface
  ui.show()

  sys.exit(app.exec_())
